### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by brianoceguera** [willyjlee/Launch-controller#1]
If a user visits the page any of the pages to open/close the relays directly through the address bar, it looks like the the PHP scripts don't check if the visit is valid before executing a command. Otherwise, anyone who knows the address of the page to actuate the ignition could ignite the rocket.

A quick way to fix this would be to use PHP's SESSION variable to store a value when a user logs in to the page, and then introduce a session check at each of the PHP scripts that open/close relays

See: [](http://php.net/manual/en/reserved.variables.session.php)
**Login page**
```
session_save_path("/public_html/launch_controller/sessions");
session_start();
$_SESSION["username"] = $usr;
$_SESSION["loggedin"] = true;
```

**Open/Close Relay Page**
```
session_save_path("("/public_html/launch_controller/sessions);
session_start();
	if($_SESSION["loggedin"] == false){
		header("Location: index.php");
		die();
	}
```

**Comment by willyjlee** [comment]
Thanks Brian.

Now each PHP script access the authentication database and verifies the password:

`$conn = mysqli_connect($srv,$user,$pass,$db);`
`$res = mysqli_query($conn, "SELECT * FROM user");`
`$row = mysqli_fetch_array($res);`

And verifies the hashed password each time from the database:
`password_verify($password,$row['password_hash'])`

The code doesn't continue if the password isn't verified.
